"""patronymic added

Revision ID: 6b6f41b897e3
Revises: 8792fa978927
Create Date: 2026-01-07 16:19:22.676828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6f41b897e3'
down_revision: Union[str, Sequence[str], None] = '8792fa978927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=320), nullable=False))
    op.add_column('users', sa.Column('surname', sa.String(length=320), nullable=False))
    op.add_column('users', sa.Column('patronymic', sa.String(length=320), nullable=False))
    op.drop_column('users', 'second_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('second_name', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    op.drop_column('users', 'patronymic')
    op.drop_column('users', 'surname')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
